"""
Makefile.py — bundled pymaketool build configuration for pytest-qemu-pic32mk
=============================================================================
This file is GENERATED/MANAGED by the pytest-qemu-pic32mk plugin.  Do NOT
edit it inside the build workspace (.pytest-qemu-build/pymake/Makefile.py);
your changes will be overwritten on the next test run.

To customise the build, set the corresponding environment variables (all are
injected automatically by the plugin from your Pic32mkConfig):

    QEMU_PROJECT_NAME    — output file prefix (default: PIC32MK-PROJECT)
    QEMU_LINKER_SCRIPT   — path to the XC32 .ld source, relative to the
                           workspace root (default: TARGET/firmware/src/
                           config/default/p32MK1024MCM100.ld)
    RELEASE              — set to "1" for an optimised release build

The workspace layout the plugin creates mirrors IDU-EMULATOR::

    <workspace>/
        TARGET/          → symlink → foreign project sources (project_src_dir)
        wrapper/         → symlink → bundled MIPS wrapper inside the package
        pymake/
            Makefile.py          ← this file
            validate_xc32_fmt3.py
            makefile.mk          (generated by pymaketool)
            srcs.mk  vars.mk  targets.mk
        gen_rw_image.py
        Release/
            Objects/
            <PROJECT_NAME>.boot.bin
            <PROJECT_NAME>.app.bin
            <PROJECT_NAME>.rw.bin
            <PROJECT_NAME>.rw.addr
"""

import os
import subprocess
from pymakelib import MKVARS, AbstractMake, Makeclass, addon
from pymakelib.clangd_addon import CompileCommandsAddon

CompileCommandsAddon.strip_flags = [
    "-fframe-base-loclist",
    "-MP",
    "-MMD",
    "-c",
]
CompileCommandsAddon.strip_flags_with_value = [
    "-mprocessor",
    "-mdfp",
    "-mreserve",
]

addon.add(CompileCommandsAddon)


# =============================================================================
# Project Configuration — controlled by environment variables injected by the
# pytest-qemu-pic32mk plugin from Pic32mkConfig fields.
# =============================================================================
PROJECT_NAME = os.environ.get("QEMU_PROJECT_NAME", "PIC32MK-PROJECT")

# Debug mode is the default. Set RELEASE=1 to build for production.
RELEASE_BUILD = os.environ.get("RELEASE", "0") == "1"

# Resolve GCC built-in include path once (for stdint.h, stddef.h with -nostdinc)
GCC_INTERNAL_INCLUDE = subprocess.check_output(
    ["mipsel-linux-gnu-gcc", "-print-file-name=include"], text=True
).strip()

# Resolve libgcc for the target ABI (provides __udivdi3 and other runtime helpers).
# -print-multi-directory returns the multilib subdir for our flags so we can
# locate the matching libgcc.a.
_LIBGCC_BASE_DIR = os.path.dirname(
    subprocess.check_output(
        ["mipsel-linux-gnu-gcc", "-print-libgcc-file-name"], text=True
    ).strip()
)
_LIBGCC_MULTIDIR = subprocess.check_output(
    [
        "mipsel-linux-gnu-gcc",
        "-march=mips32r2",
        "-mabi=32",
        "-mhard-float",
        "-mfp64",
        "-EL",
        "-print-multi-directory",
    ],
    text=True,
).strip()
LIBGCC = (
    os.path.join(_LIBGCC_BASE_DIR, "libgcc.a")
    if _LIBGCC_MULTIDIR == "."
    else os.path.join(_LIBGCC_BASE_DIR, _LIBGCC_MULTIDIR, "libgcc.a")
)

# Output directories
FOLDER_OUT = "Release/Objects/"
DIST_DIR = "Release/"

# Target files
TARGET_ELF = DIST_DIR + PROJECT_NAME + ".elf"
TARGET_MAP = DIST_DIR + PROJECT_NAME + ".map"
# Two flat images for the QEMU pic32mk machine:
#   - boot.bin    → loaded via -bios into BFLASH1 @ 0xBFC00000 (only .reset)
#   - app.bin     → loaded into program flash @ 0x1D000000 (kseg0 LMAs)
# A single flat .bin spanning both regions would be ~1 GB because of the
# address gap, and must NOT be generated.
TARGET_BOOT_BIN = DIST_DIR + PROJECT_NAME + ".boot.bin"
TARGET_PFLASH_BIN = DIST_DIR + PROJECT_NAME + ".app.bin"
# Initialized .data segment image — extracted from ELF RW LOAD segment.
# QEMU loads this raw blob into physical RAM via -device loader so that
# global variables are initialized correctly when running with -bios flat
# binaries (our crt0 only zeroes .bss).
TARGET_RAM_BIN = DIST_DIR + PROJECT_NAME + ".rw.bin"

# Linker script
# The XC32-generated .ld uses OUTPUT_ARCH(pic32mx) and C preprocessor
# directives (#if/#endif) which mipsel-linux-gnu-ld cannot handle.
# We preprocess it with gcc -E -P and patch the XC32-specific constructs.
# QEMU_LINKER_SCRIPT is set by the plugin to "TARGET/<linker_script>"
# where <linker_script> is Pic32mkConfig.linker_script (relative to
# project_src_dir).  The TARGET/ symlink resolves to project_src_dir.
_LINKER_SCRIPT_SRC = os.environ.get(
    "QEMU_LINKER_SCRIPT",
    "TARGET/firmware/src/config/default/p32MK1024MCM100.ld",
)
LINKER_SCRIPT = DIST_DIR + "linker_script.ld"
os.makedirs(DIST_DIR, exist_ok=True)
_ld_content = subprocess.check_output(
    ["mipsel-linux-gnu-gcc", "-E", "-P", "-x", "c", _LINKER_SCRIPT_SRC], text=True
)
# Fix XC32-specific constructs that mipsel-linux-gnu-ld doesn't support:
#   OUTPUT_ARCH(pic32mx) → mips (GNU ld uses "mips" for MIPS32)
#   OPTIONAL("...") → removed (GNU ld has no OPTIONAL() built-in)
import re as _re

_ld_content = _ld_content.replace("OUTPUT_ARCH(pic32mx)", "OUTPUT_ARCH(mips)")
_ld_content = _re.sub(r"OPTIONAL\s*\([^)]*\)\s*;?\n?", "", _ld_content)
# Inject .simple_tlb_refill section at EBASE+0 (0x9D000000) so that objcopy
# starts the program-flash binary at the correct base address.  Without this,
# the lowest section is .app_excpt at EBASE+0x180 and the flat binary is
# shifted by -0x180 relative to QEMU's load address.
_TLB_SECTION = (
    "\n  .simple_tlb_refill _SIMPLE_TLB_REFILL_EXCPT_ADDR :\n"
    "  {\n"
    "    KEEP(*(.simple_tlb_refill_excpt))\n"
    "  } > kseg0_exception_mem\n"
)
_ld_content = _ld_content.replace(
    ".app_excpt _GEN_EXCPT_ADDR :",
    _TLB_SECTION + "  .app_excpt _GEN_EXCPT_ADDR :",
)
# Insert .vector_dispatch section at the START of .vectors (before .vector_0).
# This places the software interrupt dispatcher at EBASE+0x200 — the address
# where ALL interrupts land when IntCtl.VS=0 (single-vector mode).
_ld_content = _ld_content.replace(
    "    __vector_offset_0 = (DEFINED(__vector_dispatch_0)"
    " ? (. - _ebase_address) : __vector_offset_default);",
    "    KEEP(*(.vector_dispatch))\n"
    "    . = ALIGN(4) ;\n"
    "    __vector_offset_0 = (DEFINED(__vector_dispatch_0)"
    " ? (. - _ebase_address) : __vector_offset_default);",
)
with open(LINKER_SCRIPT, "w") as _f:
    _f.write(_ld_content)


@Makeclass
class Project(AbstractMake):
    """PIC32MK firmware — QEMU emulator build (pytest-qemu-pic32mk managed)"""

    def getProjectSettings(self, **kwargs) -> dict:
        return {
            "PROJECT_NAME": PROJECT_NAME,
            "FOLDER_OUT": FOLDER_OUT,
        }

    def getTargetsScript(self, **kwargs) -> dict:
        return {
            "TARGET": {
                "LOGKEY": "LD",
                "FILE": TARGET_ELF,
                "SCRIPT": [
                    MKVARS.LD,
                    "-m",
                    "elf32ltsmip",
                    "-T",
                    LINKER_SCRIPT,
                    "--gc-sections",
                    # Redirect vApplicationIdleHook() → __wrap_vApplicationIdleHook()
                    # so wrapper/stubs/freertos_overrides.c can override the empty
                    # stub without triggering a duplicate-symbol error.
                    "--wrap=vApplicationIdleHook",
                    "-Map=" + TARGET_MAP,
                    "-o",
                    "$@",
                    MKVARS.OBJECTS,
                    LIBGCC,
                ],
            },
            # Boot flash image — only the .reset stub at 0xBFC00000 (~152 B).
            # Loaded by the QEMU pic32mk machine via -bios into BFLASH1.
            "TARGET_BOOT_BIN": {
                "LOGKEY": "BOOT",
                "FILE": TARGET_BOOT_BIN,
                "SCRIPT": [
                    MKVARS.OBJCOPY,
                    "-O",
                    "binary",
                    "-j",
                    ".reset",
                    MKVARS.TARGET,
                    TARGET_BOOT_BIN,
                ],
            },
            # Program flash image — kseg0 sections (LMA 0x9Dxxxxxx).
            "TARGET_PFLASH_BIN": {
                "LOGKEY": "PFLASH",
                "FILE": TARGET_PFLASH_BIN,
                "SCRIPT": [
                    MKVARS.OBJCOPY,
                    "-O",
                    "binary",
                    "--wildcard",
                    "-j",
                    ".simple_tlb_refill*",
                    "-j",
                    ".app_excpt",
                    "-j",
                    ".vectors",
                    "-j",
                    ".text*",
                    "-j",
                    ".rodata*",
                    "-j",
                    ".dinit*",
                    MKVARS.TARGET,
                    TARGET_PFLASH_BIN,
                ],
            },
            # Initialized .data image for QEMU RAM preload.
            "TARGET_RAM_BIN": {
                "LOGKEY": "RWINIT",
                "FILE": TARGET_RAM_BIN,
                "SCRIPT": ["python3", "gen_rw_image.py", MKVARS.TARGET, TARGET_RAM_BIN],
            },
            "TARGET_CHECKS": {
                "LOGKEY": "CHK",
                "FILE": "CHECKS",
                "SCRIPT": [
                    "python3 pymake/validate_xc32_fmt3.py --objects-dir " + FOLDER_OUT
                ],
            },
        }

    def getCompilerSet(self, **kwargs) -> dict:
        prefix = "mipsel-linux-gnu-"
        return {
            "CC": prefix + "gcc",
            "CXX": prefix + "g++",
            "LD": prefix + "ld",
            "AR": prefix + "ar",
            "AS": prefix + "as",
            "OBJCOPY": prefix + "objcopy",
            "SIZE": prefix + "size",
            "OBJDUMP": prefix + "objdump",
            "NM": prefix + "nm",
            "STRIP": prefix + "strip",
            "READELF": prefix + "readelf",
            "INCLUDES": [
                GCC_INTERNAL_INCLUDE,
                "/usr/mipsel-linux-gnu/include",
            ],
        }

    def getCompilerOpts(self, **kwargs) -> dict:
        return {
            "MACROS": {"MCU_PIC32MK1024GPE100": 1, "__mips_hard_float": 1}
            | ({} if RELEASE_BUILD else {"DEBUG": "1"}),
            "MACHINE-OPTS": [
                "-march=mips32r2",
                "-mdspr2",
                "-mhard-float",
                "-mfp64",
                "-mno-micromips",
                "-mabi=32",
                "-EL",
                "-G",
                "0",
                "-mno-abicalls",
            ],
            "OPTIMIZE-OPTS": ["-O1"] if RELEASE_BUILD else ["-Og"],
            "OPTIONS": [
                "-ffreestanding",
                "-fno-builtin",
                "-nostdlib",
                "-nostdinc",
                "-ffunction-sections",
                "-fdata-sections",
            ]
            + ([] if RELEASE_BUILD else ["-fno-omit-frame-pointer"]),
            "DEBUGGING-OPTS": ["-g"] if RELEASE_BUILD else ["-g3", "-gdwarf-2"],
            "PREPROCESSOR-OPTS": [],
            "WARNINGS-OPTS": [
                "-Wno-unused-parameter",
                "-Wno-sign-compare",
            ],
            "CONTROL-C-OPTS": ["-c"],
            "GENERAL-OPTS": [
                "-isystem",
                GCC_INTERNAL_INCLUDE,
                "-isystem",
                "/usr/mipsel-linux-gnu/include",
                "-include",
                "wrapper/stubs/stdlib.h",
            ],
        }

    def getLinkerOpts(self, **kwargs) -> dict:
        return {
            "LINKER-SCRIPT": [],
            "MACHINE-OPTS": [],
            "GENERAL-OPTS": [],
            "LINKER-OPTS": [],
        }
