"""Firmware build runner for pytest-qemu-pic32mk (workspace mode only).

Invoked once per pytest session via the ``_pic32mk_build`` autouse fixture.

Set ``Pic32mkConfig.project_src_dir`` to the firmware source root.  The plugin
creates a managed workspace at ``.pytest-qemu-build/``, symlinks the sources as
``TARGET/`` and the bundled wrapper as ``wrapper/``, copies the bundled
``Makefile.py`` into ``pymake/``, then drives ``pymaketool all`` and
``make -f pymake/makefile.mk all``.  No ``Makefile`` or pymaketool config is
needed in the consumer project.

Call chain::

    pytest session starts
        → _pic32mk_build fixture (plugin.py)
            → build_firmware(config, rootdir)
                → _build_workspace(config, rootdir)
                    → _setup_workspace()  — dirs, scripts, symlinks
                    → pymaketool all      — generates srcs.mk / vars.mk / targets.mk
                    → make -f pymake/makefile.mk all  — compile, link, extract
                    → config.release_dir = workspace/Release
        → qemu_proc fixture starts QEMU with Release/*.boot.bin etc.
        → tests run
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from .config import Pic32mkConfig


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_build_assets_dir() -> Path:
    """Return the directory containing the bundled Makefile.py and scripts."""
    return Path(__file__).parent / "build_assets"


def _replace_symlink(link: Path, target: Path) -> None:
    """Remove any existing entry at *link* and create a fresh symlink → *target*."""
    if link.is_symlink():
        link.unlink()
    elif link.exists():
        shutil.rmtree(str(link))
    link.symlink_to(target)


def _setup_workspace(config: Pic32mkConfig, rootdir: Path) -> Path:
    """Create (or refresh) the isolated build workspace and return its path.

    The workspace layout mirrors IDU-EMULATOR::

        <workspace>/
            TARGET/          → symlink → config.project_src_dir
            wrapper/         → symlink → bundled wrapper in this package
            pymake/
                Makefile.py          (copied from build_assets each run)
                validate_xc32_fmt3.py
                makefile.mk          (generated by pymaketool)
                srcs.mk  vars.mk  targets.mk
            gen_rw_image.py  (copied from build_assets each run)
            Release/
                Objects/
    """
    # Resolve workspace path
    if config.build_workspace is not None:
        workspace = Path(str(config.build_workspace))
        if not workspace.is_absolute():
            workspace = rootdir / workspace
    else:
        workspace = rootdir / ".pytest-qemu-build"
    workspace = workspace.resolve()

    # Directory structure
    (workspace / "pymake").mkdir(parents=True, exist_ok=True)
    (workspace / "Release" / "Objects").mkdir(parents=True, exist_ok=True)

    # Copy build scripts (overwrite every run so plugin updates are picked up)
    assets = _get_build_assets_dir()
    shutil.copy2(assets / "Makefile.py", workspace / "pymake" / "Makefile.py")
    shutil.copy2(
        assets / "validate_xc32_fmt3.py",
        workspace / "pymake" / "validate_xc32_fmt3.py",
    )
    # makefile.mk is a static template (not generated by pymaketool) — it
    # includes the pymaketool-generated srcs.mk / vars.mk / targets.mk.
    shutil.copy2(assets / "makefile.mk", workspace / "pymake" / "makefile.mk")
    shutil.copy2(assets / "gen_rw_image.py", workspace / "gen_rw_image.py")

    # TARGET/ → foreign project sources
    project_src = Path(str(config.project_src_dir)).resolve()
    if not project_src.is_dir():
        pytest.fail(
            f"[pytest-qemu-pic32mk] project_src_dir not found: {project_src}\n"
            "Set Pic32mkConfig(project_src_dir=...) to the firmware source root."
        )
    _replace_symlink(workspace / "TARGET", project_src)

    # wrapper/ → bundled MIPS wrapper inside this package
    bundled_wrapper = Path(__file__).parent / "wrapper"

    needs_hybrid = config.startup_dir or config.stubs_dir or config.xc32_dir
    if not needs_hybrid:
        # Default: single symlink to the entire bundled wrapper.
        _replace_symlink(workspace / "wrapper", bundled_wrapper)
    else:
        # One or more sub-directories are overridden; wrapper/ becomes a real
        # directory with per-subdirectory symlinks so unoverridden parts stay bundled.
        def _resolved_dir(override: "str | Path | None", name: str, hint: str) -> Path:
            if override is None:
                return bundled_wrapper / name
            p = Path(str(override)).resolve()
            if not p.is_dir():
                pytest.fail(
                    f"[pytest-qemu-pic32mk] {name}_dir not found: {p}\n{hint}"
                )
            return p

        startup_src = _resolved_dir(
            config.startup_dir, "startup",
            "Set Pic32mkConfig(startup_dir=...) to a directory containing "
            "crt0.S, irq_dispatch.S, and mk.py.",
        )
        stubs_src = _resolved_dir(
            config.stubs_dir, "stubs",
            "Set Pic32mkConfig(stubs_dir=...) to a directory containing "
            "the replacement stubs headers and sources.",
        )
        xc32_src = _resolved_dir(
            config.xc32_dir, "xc32",
            "Set Pic32mkConfig(xc32_dir=...) to a directory containing "
            "the replacement xc32/xc.h compatibility headers.",
        )

        wrapper_dir = workspace / "wrapper"
        # Remove any previous single-symlink before creating a real directory.
        if wrapper_dir.is_symlink():
            wrapper_dir.unlink()
        wrapper_dir.mkdir(exist_ok=True)
        _replace_symlink(wrapper_dir / "__init__.py", bundled_wrapper / "__init__.py")
        _replace_symlink(wrapper_dir / "startup", startup_src)
        _replace_symlink(wrapper_dir / "stubs", stubs_src)
        _replace_symlink(wrapper_dir / "xc32", xc32_src)

    return workspace


def _build_workspace(config: Pic32mkConfig, rootdir: Path) -> None:
    """Drive pymaketool + make inside the managed workspace."""
    workspace = _setup_workspace(config, rootdir)

    # QEMU_LINKER_SCRIPT is always TARGET/<linker_script> so that the bundled
    # Makefile.py finds the XC32 .ld through the TARGET/ symlink.
    linker_script_path = f"TARGET/{config.linker_script}"

    env = os.environ.copy()
    env.update(config.build_env)
    env["QEMU_PROJECT_NAME"] = config.project_name
    env["QEMU_LINKER_SCRIPT"] = linker_script_path

    print(
        f"\n[pytest-qemu-pic32mk] Building firmware (workspace mode)\n"
        f"  workspace : {workspace}\n"
        f"  project   : {config.project_name}\n"
        f"  sources   : {config.project_src_dir}\n"
        f"  linker    : {linker_script_path}",
        flush=True,
    )

    # Step 1: pymaketool regenerates srcs.mk / vars.mk / targets.mk
    pymaketool_bin = shutil.which("pymaketool") or "pymaketool"
    result = subprocess.run(
        [pymaketool_bin, "all"],
        cwd=str(workspace),
        env=env,
    )
    if result.returncode != 0:
        pytest.fail(
            f"[pytest-qemu-pic32mk] pymaketool failed (exit {result.returncode}).\n"
            f"Workspace: {workspace}\n"
            "Fix the build configuration errors above and re-run pytest."
        )

    # Step 2: make compiles, links, and extracts the three binary images
    result = subprocess.run(
        ["make", "-f", "pymake/makefile.mk", "all"],
        cwd=str(workspace),
        env=env,
    )
    if result.returncode != 0:
        pytest.fail(
            f"[pytest-qemu-pic32mk] Firmware compilation failed (exit {result.returncode}).\n"
            f"Workspace: {workspace}\n"
            "Fix the compilation errors above and re-run pytest."
        )

    # Redirect artifact discovery so qemu.py picks up the built binaries
    config.release_dir = workspace / "Release"

    # Symlink compile_commands.json to workspace root so clangd can find it
    # by pointing CompilationDatabase at the workspace directory.
    cc_src = workspace / "pymake" / "compile_commands.json"
    cc_link = workspace / "compile_commands.json"
    if cc_src.exists():
        _replace_symlink(cc_link, cc_src)

    print("[pytest-qemu-pic32mk] Build OK (workspace).\n", flush=True)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_firmware(config: Pic32mkConfig, rootdir: Path) -> None:
    """Compile the firmware for the current project using workspace mode.

    Requires ``config.project_src_dir`` to be set.  The plugin creates an
    isolated build workspace, symlinks the firmware sources as ``TARGET/``,
    injects the bundled ``wrapper/``, and drives ``pymaketool`` + ``make``.

    Args:
        config:   Active :class:`Pic32mkConfig`.
        rootdir:  The pytest root directory (``config.rootdir`` in the plugin).
                  Used to resolve relative paths.

    Raises:
        pytest.fail: immediately if the build command exits non-zero.
    """
    if not config.build:
        return

    if config.project_src_dir is None:
        pytest.fail(
            "[pytest-qemu-pic32mk] Pic32mkConfig.project_src_dir is required.\n"
            "Set it to the firmware source root to enable workspace mode.\n"
            "Example: Pic32mkConfig(project_src_dir=Path(__file__).parent.parent)"
        )

    _build_workspace(config, rootdir)

