"""Firmware build runner for pytest-qemu-pic32mk.

Invoked once per pytest session, before QEMU is launched.  Supports two modes:

**Workspace mode** (recommended for foreign projects):
    Set ``Pic32mkConfig.project_src_dir`` to the foreign firmware source root.
    The plugin creates a managed workspace at ``.pytest-qemu-build/``, symlinks
    the firmware sources as ``TARGET/`` and the bundled wrapper as ``wrapper/``,
    copies the bundled ``Makefile.py`` into ``pymake/``, then drives
    ``pymaketool all`` and ``make -f pymake/makefile.mk all`` transparently.
    No ``Makefile`` or pymaketool configuration is needed in the foreign project.

**Custom build mode** (default when ``project_src_dir`` is ``None``):
    Runs ``build_cmd`` (default: ``make``) in ``build_workspace``.
    If the project contains a ``Makefile.py`` but ``pymake/makefile.mk`` has not
    been generated yet, ``pymaketool`` is invoked automatically before
    ``build_cmd`` — eliminating the ``make: pymake/makefile.mk: No such file``
    error that occurs when ``make`` is called before pymaketool has run.

In both modes, build output is streamed live to stdout so the user can see
compiler warnings and errors directly in the pytest run.  A non-zero exit code
raises ``pytest.fail`` immediately, aborting the session before any test starts.

Typical workspace call chain
-----------------------------
::

    pytest session starts
        → _pic32mk_build fixture (plugin.py)
            → build_firmware(config, rootdir)
                → _build_workspace(config, rootdir)
                    → _setup_workspace()  — creates dirs, copies scripts, symlinks
                    → pymaketool all      — generates srcs.mk / vars.mk / targets.mk
                    → make -f pymake/makefile.mk all  — compiles, links, extracts
                    → config.release_dir = workspace/Release  (mutates for QEMU)
        → qemu_proc fixture starts QEMU with Release/*.boot.bin etc.
        → tests run
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from .config import Pic32mkConfig


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_build_assets_dir() -> Path:
    """Return the directory containing the bundled Makefile.py and scripts."""
    return Path(__file__).parent / "build_assets"


def _replace_symlink(link: Path, target: Path) -> None:
    """Remove any existing entry at *link* and create a fresh symlink → *target*."""
    if link.is_symlink():
        link.unlink()
    elif link.exists():
        shutil.rmtree(str(link))
    link.symlink_to(target)


def _setup_workspace(config: Pic32mkConfig, rootdir: Path) -> Path:
    """Create (or refresh) the isolated build workspace and return its path.

    The workspace layout mirrors IDU-EMULATOR::

        <workspace>/
            TARGET/          → symlink → config.project_src_dir
            wrapper/         → symlink → bundled wrapper in this package
            pymake/
                Makefile.py          (copied from build_assets each run)
                validate_xc32_fmt3.py
                makefile.mk          (generated by pymaketool)
                srcs.mk  vars.mk  targets.mk
            gen_rw_image.py  (copied from build_assets each run)
            Release/
                Objects/
    """
    # Resolve workspace path
    if config.build_workspace is not None:
        workspace = Path(str(config.build_workspace))
        if not workspace.is_absolute():
            workspace = rootdir / workspace
    else:
        workspace = rootdir / ".pytest-qemu-build"
    workspace = workspace.resolve()

    # Directory structure
    (workspace / "pymake").mkdir(parents=True, exist_ok=True)
    (workspace / "Release" / "Objects").mkdir(parents=True, exist_ok=True)

    # Copy build scripts (overwrite every run so plugin updates are picked up)
    assets = _get_build_assets_dir()
    shutil.copy2(assets / "Makefile.py", workspace / "pymake" / "Makefile.py")
    shutil.copy2(
        assets / "validate_xc32_fmt3.py",
        workspace / "pymake" / "validate_xc32_fmt3.py",
    )
    # makefile.mk is a static template (not generated by pymaketool) — it
    # includes the pymaketool-generated srcs.mk / vars.mk / targets.mk.
    shutil.copy2(assets / "makefile.mk", workspace / "pymake" / "makefile.mk")
    shutil.copy2(assets / "gen_rw_image.py", workspace / "gen_rw_image.py")

    # TARGET/ → foreign project sources
    project_src = Path(str(config.project_src_dir)).resolve()
    if not project_src.is_dir():
        pytest.fail(
            f"[pytest-qemu-pic32mk] project_src_dir not found: {project_src}\n"
            "Set Pic32mkConfig(project_src_dir=...) to the firmware source root."
        )
    _replace_symlink(workspace / "TARGET", project_src)

    # wrapper/ → bundled MIPS wrapper inside this package
    bundled_wrapper = Path(__file__).parent / "wrapper"

    if config.startup_dir is None:
        # Default: single symlink to the entire bundled wrapper.
        _replace_symlink(workspace / "wrapper", bundled_wrapper)
    else:
        # Custom startup: wrapper/ is a real directory; startup/ is redirected
        # to the caller-supplied directory while everything else stays bundled.
        custom_startup = Path(str(config.startup_dir)).resolve()
        if not custom_startup.is_dir():
            pytest.fail(
                f"[pytest-qemu-pic32mk] startup_dir not found: {custom_startup}\n"
                "Set Pic32mkConfig(startup_dir=...) to a directory containing "
                "crt0.S, irq_dispatch.S, and mk.py."
            )
        wrapper_dir = workspace / "wrapper"
        # Remove any previous single-symlink before creating a real directory.
        if wrapper_dir.is_symlink():
            wrapper_dir.unlink()
        wrapper_dir.mkdir(exist_ok=True)
        _replace_symlink(wrapper_dir / "__init__.py", bundled_wrapper / "__init__.py")
        _replace_symlink(wrapper_dir / "startup", custom_startup)
        _replace_symlink(wrapper_dir / "stubs", bundled_wrapper / "stubs")
        _replace_symlink(wrapper_dir / "xc32", bundled_wrapper / "xc32")

    return workspace


def _build_workspace(config: Pic32mkConfig, rootdir: Path) -> None:
    """Drive pymaketool + make inside the managed workspace."""
    workspace = _setup_workspace(config, rootdir)

    # QEMU_LINKER_SCRIPT is always TARGET/<linker_script> so that the bundled
    # Makefile.py finds the XC32 .ld through the TARGET/ symlink.
    linker_script_path = f"TARGET/{config.linker_script}"

    env = os.environ.copy()
    env.update(config.build_env)
    env["QEMU_PROJECT_NAME"] = config.project_name
    env["QEMU_LINKER_SCRIPT"] = linker_script_path

    print(
        f"\n[pytest-qemu-pic32mk] Building firmware (workspace mode)\n"
        f"  workspace : {workspace}\n"
        f"  project   : {config.project_name}\n"
        f"  sources   : {config.project_src_dir}\n"
        f"  linker    : {linker_script_path}",
        flush=True,
    )

    # Step 1: pymaketool regenerates srcs.mk / vars.mk / targets.mk
    pymaketool_bin = shutil.which("pymaketool") or "pymaketool"
    result = subprocess.run(
        [pymaketool_bin, "all"],
        cwd=str(workspace),
        env=env,
    )
    if result.returncode != 0:
        pytest.fail(
            f"[pytest-qemu-pic32mk] pymaketool failed (exit {result.returncode}).\n"
            f"Workspace: {workspace}\n"
            "Fix the build configuration errors above and re-run pytest."
        )

    # Step 2: make compiles, links, and extracts the three binary images
    result = subprocess.run(
        ["make", "-f", "pymake/makefile.mk", "all"],
        cwd=str(workspace),
        env=env,
    )
    if result.returncode != 0:
        pytest.fail(
            f"[pytest-qemu-pic32mk] Firmware compilation failed (exit {result.returncode}).\n"
            f"Workspace: {workspace}\n"
            "Fix the compilation errors above and re-run pytest."
        )

    # Redirect artifact discovery so qemu.py picks up the built binaries
    config.release_dir = workspace / "Release"

    print("[pytest-qemu-pic32mk] Build OK (workspace).\n", flush=True)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_firmware(config: Pic32mkConfig, rootdir: Path) -> None:
    """Compile the firmware for the current project.

    Dispatches to *workspace mode* when ``config.project_src_dir`` is set,
    otherwise falls back to the custom ``build_cmd`` / ``build_workspace`` mode.

    Args:
        config:   Active :class:`Pic32mkConfig`.
        rootdir:  The pytest root directory (``config.rootdir`` in the plugin).
                  Used to resolve relative paths.

    Raises:
        pytest.fail: immediately if the build command exits non-zero.
    """
    if not config.build:
        return

    # ---- workspace mode ----
    if config.project_src_dir is not None:
        _build_workspace(config, rootdir)
        return

    # ---- custom build mode ----
    # build_workspace is the directory containing Makefile.py / Makefile.
    # Relative paths are resolved from the pytest rootdir.
    if config.build_workspace is not None:
        build_dir = Path(str(config.build_workspace))
        if not build_dir.is_absolute():
            build_dir = rootdir / build_dir
    else:
        build_dir = rootdir
    build_dir = build_dir.resolve()

    if not build_dir.is_dir():
        pytest.fail(
            f"[pytest-qemu-pic32mk] build_workspace not found: {build_dir}\n"
            "Set Pic32mkConfig(build_workspace=...) to the directory containing "
            "your Makefile.py / Makefile."
        )

    env = os.environ.copy()
    env.update(config.build_env)

    # If the project has a Makefile.py (at root or in pymake/) but
    # pymake/makefile.mk has not been generated yet, run pymaketool first.
    # This prevents the common "make: pymake/makefile.mk: No such file or
    # directory" error that occurs when make is invoked before pymaketool.
    makefile_mk = build_dir / "pymake" / "makefile.mk"
    makefile_py_root = build_dir / "Makefile.py"
    makefile_py_pymake = build_dir / "pymake" / "Makefile.py"
    has_makefile_py = makefile_py_root.exists() or makefile_py_pymake.exists()

    if has_makefile_py and not makefile_mk.exists():
        pymaketool_bin = shutil.which("pymaketool") or "pymaketool"
        print(
            f"\n[pytest-qemu-pic32mk] Generating pymake/makefile.mk via pymaketool"
            f"  (cwd={build_dir})",
            flush=True,
        )
        result = subprocess.run(
            [pymaketool_bin, "all"],
            cwd=str(build_dir),
            env=env,
        )
        if result.returncode != 0:
            pytest.fail(
                f"[pytest-qemu-pic32mk] pymaketool failed (exit {result.returncode}).\n"
                f"Directory: {build_dir}\n"
                "Fix the Makefile.py errors above and re-run pytest."
            )

    print(
        f"\n[pytest-qemu-pic32mk] Building firmware for QEMU: {config.build_cmd!r}"
        f"  (cwd={build_dir})",
        flush=True,
    )

    result = subprocess.run(
        config.build_cmd,
        shell=True,
        cwd=str(build_dir),
        env=env,
    )

    if result.returncode != 0:
        pytest.fail(
            f"[pytest-qemu-pic32mk] Firmware build failed "
            f"(exit {result.returncode}).\n"
            f"Command: {config.build_cmd}\n"
            f"Directory: {build_dir}\n"
            "Fix the compilation errors above and re-run pytest."
        )

    print("[pytest-qemu-pic32mk] Build OK.\n", flush=True)

